version: 1
user: "hawksifht"
lists:
  - slug: "python" # taken from /stars/<user>/lists/<slug>
    title: "Awesome Python Things"
    tagline: "Make yourself an awesome pythonista"
    min_stars: 10
    stale_months: 90
    badges:
      - "https://img.shields.io/badge/awesome-yes-brightgreen"
